<?php

namespace Database\Seeders;

use App\Models\Inherentrisiko;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InherentrisikoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kritikal' => 'P1','kerawanan' => 'Using Default Credentials'],
            ['kritikal' => 'P1','kerawanan' => 'File Inclusion'],
            ['kritikal' => 'P1','kerawanan' => 'Remote Code Execution (RCE)'],
            ['kritikal' => 'P1','kerawanan' => 'SQL Injection'],
            ['kritikal' => 'P1','kerawanan' => 'XML External Entity Injection (XXE)'],
            ['kritikal' => 'P1','kerawanan' => 'Authentication Bypass'],
            ['kritikal' => 'P1','kerawanan' => 'Disclosure of Secrets'],
            ['kritikal' => 'P1','kerawanan' => 'Insecure Direct Object References (IDOR)'],
            ['kritikal' => 'P1','kerawanan' => 'Command Injection'],
            ['kritikal' => 'P1','kerawanan' => 'Hardcoded Password'],
            ['kritikal' => 'P1','kerawanan' => 'Infotainment'],
            ['kritikal' => 'P1','kerawanan' => 'RF Hub'],
            ['kritikal' => 'P1','kerawanan' => 'Large Language Model (LLM) Security'],
            ['kritikal' => 'P2','kerawanan' => 'Server-Side Request Forgery (SSRF)'],
            ['kritikal' => 'P2','kerawanan' => 'OAuth Misconfiguration'],
            ['kritikal' => 'P2','kerawanan' => 'Weak Password Reset Implementation'],
            ['kritikal' => 'P2','kerawanan' => 'Stored'],
            ['kritikal' => 'P2','kerawanan' => 'Insecure Direct Object References (IDOR)'],
            ['kritikal' => 'P2','kerawanan' => 'Application-Wide'],
            ['kritikal' => 'P2','kerawanan' => 'Critical Impact and/or Easy Difficulty'],
            ['kritikal' => 'P2','kerawanan' => 'Weakness in physical access control'],
            ['kritikal' => 'P2','kerawanan' => 'Hardcoded Password'],
            ['kritikal' => 'P2','kerawanan' => 'Over-Permissioned Credentials on Storage'],
            ['kritikal' => 'P2','kerawanan' => 'Local Administrator on default environment'],
            ['kritikal' => 'P2','kerawanan' => 'Key Reuse'],
            ['kritikal' => 'P2','kerawanan' => 'Infotainment'],
            ['kritikal' => 'P2','kerawanan' => 'RF Hub'],
            ['kritikal' => 'P2','kerawanan' => 'Large Language Model (LLM) Security'],
            ['kritikal' => 'P3','kerawanan' => 'Server-Side Request Forgery (SSRF)'],
            ['kritikal' => 'P3','kerawanan' => 'Misconfigured DNS'],
            ['kritikal' => 'P3','kerawanan' => 'Mail Server Misconfiguration'],
            ['kritikal' => 'P3','kerawanan' => 'HTTP Response Manipulation'],
            ['kritikal' => 'P3','kerawanan' => 'Content Spoofing'],
            ['kritikal' => 'P3','kerawanan' => 'Second Factor Authentication (2FA) Bypass'],
            ['kritikal' => 'P3','kerawanan' => 'Session Fixation'],
            ['kritikal' => 'P3','kerawanan' => 'Disclosure of Secrets'],
            ['kritikal' => 'P3','kerawanan' => 'EXIF Geolocation Data Not Stripped From Uploaded Images'],
            ['kritikal' => 'P3','kerawanan' => 'Stored'],
            ['kritikal' => 'P3','kerawanan' => 'Stored'],
            ['kritikal' => 'P3','kerawanan' => 'Reflected'],
            ['kritikal' => 'P3','kerawanan' => 'Insecure Direct Object References (IDOR)'],
            ['kritikal' => 'P3','kerawanan' => 'High Impact and/or Medium Difficulty'],
            ['kritikal' => 'P3','kerawanan' => 'Weakness in Firmware Updates'],
            ['kritikal' => 'P3','kerawanan' => 'Shared Credentials on Storage'],
            ['kritikal' => 'P3','kerawanan' => 'Insecure Key Generation'],
            ['kritikal' => 'P3','kerawanan' => 'Broken Cryptography'],
            ['kritikal' => 'P3','kerawanan' => 'Binary Planting'],
            ['kritikal' => 'P3','kerawanan' => 'Infotainment'],
            ['kritikal' => 'P3','kerawanan' => 'Infotainment'],
            ['kritikal' => 'P3','kerawanan' => 'RF Hub'],
            ['kritikal' => 'P3','kerawanan' => 'Battery Management System'],
            ['kritikal' => 'P3','kerawanan' => 'Immobilizer'],
            ['kritikal' => 'P3','kerawanan' => 'Automatic Braking System (ABS)'],
            ['kritikal' => 'P4','kerawanan' => 'Misconfigured DNS'],
            ['kritikal' => 'P4','kerawanan' => 'Mail Server Misconfiguration'],
            ['kritikal' => 'P4','kerawanan' => 'Database Management System (DBMS) Misconfiguration'],
            ['kritikal' => 'P4','kerawanan' => 'Lack of Password Confirmation'],
            ['kritikal' => 'P4','kerawanan' => 'No Rate Limiting on Form'],
            ['kritikal' => 'P4','kerawanan' => 'Missing Secure or HTTPOnly Cookie Flag'],
            ['kritikal' => 'P4','kerawanan' => 'Clickjacking'],
            ['kritikal' => 'P4','kerawanan' => 'OAuth Misconfiguration'],
            ['kritikal' => 'P4','kerawanan' => 'CAPTCHA'],
            ['kritikal' => 'P4','kerawanan' => 'Lack of Security Headers'],
            ['kritikal' => 'P4','kerawanan' => 'Web Application Firewall (WAF) Bypass'],
            ['kritikal' => 'P4','kerawanan' => 'Content Spoofing'],
            ['kritikal' => 'P4','kerawanan' => 'Server-Side Template Injection (SSTI)'],
            ['kritikal' => 'P4','kerawanan' => 'Cleartext Transmission of Session Token'],
            ['kritikal' => 'P4','kerawanan' => 'Weak Login Function'],
            ['kritikal' => 'P4','kerawanan' => 'Failure to Invalidate Session'],
            ['kritikal' => 'P4','kerawanan' => 'Weak Registration Implementation'],
            ['kritikal' => 'P4','kerawanan' => 'Disclosure of Secrets'],
            ['kritikal' => 'P4','kerawanan' => 'EXIF Geolocation Data Not Stripped From Uploaded Images'],
            ['kritikal' => 'P4','kerawanan' => 'Visible Detailed Error/Debug Page'],
            ['kritikal' => 'P4','kerawanan' => 'Token Leakage via Referer'],
            ['kritikal' => 'P4','kerawanan' => 'Sensitive Token in URL'],
            ['kritikal' => 'P4','kerawanan' => 'Weak Password Reset Implementation'],
            ['kritikal' => 'P4','kerawanan' => 'Via localStorage/sessionStorage'],
            ['kritikal' => 'P4','kerawanan' => 'Stored'],
            ['kritikal' => 'P4','kerawanan' => 'Referer'],
            ['kritikal' => 'P4','kerawanan' => 'Universal (UXSS)'],
            ['kritikal' => 'P4','kerawanan' => 'Off-Domain'],
            ['kritikal' => 'P4','kerawanan' => 'Insecure Direct Object References (IDOR)'],
            ['kritikal' => 'P4','kerawanan' => 'Username/Email Enumeration'],
            ['kritikal' => 'P4','kerawanan' => 'Open Redirect'],
            ['kritikal' => 'P4','kerawanan' => 'No Password Policy'],
            ['kritikal' => 'P4','kerawanan' => 'Weak Password Reset Implementation'],
            ['kritikal' => 'P4','kerawanan' => 'Weak 2FA Implementation'],
            ['kritikal' => 'P4','kerawanan' => 'Weak 2FA Implementation'],
            ['kritikal' => 'P4','kerawanan' => 'Sensitive Application Data Stored Unencrypted'],
            ['kritikal' => 'P4','kerawanan' => 'Server-Side Credentials Storage'],
            ['kritikal' => 'P4','kerawanan' => 'Executable Download'],
            ['kritikal' => 'P4','kerawanan' => 'Insufficient Entropy'],
            ['kritikal' => 'P4','kerawanan' => 'Insufficient Verification of Data Authenticity'],
            ['kritikal' => 'P4','kerawanan' => 'Insecure Key Generation'],
            ['kritikal' => 'P4','kerawanan' => 'Key Reuse'],
            ['kritikal' => 'P4','kerawanan' => 'Broken Cryptography'],
            ['kritikal' => 'P4','kerawanan' => 'Side-Channel Attack'],
            ['kritikal' => 'P4','kerawanan' => 'Use of Expired Cryptographic Key (or Certificate)'],
            ['kritikal' => 'P4','kerawanan' => 'Unnecessary Data Collection'],
            ['kritikal' => 'P4','kerawanan' => 'RF Hub'],
            ['kritikal' => 'P4','kerawanan' => 'CAN'],
            ['kritikal' => 'P4','kerawanan' => 'CAN'],
            ['kritikal' => 'P4','kerawanan' => 'Battery Management System'],
            ['kritikal' => 'P4','kerawanan' => 'GNSS / GPS'],
            ['kritikal' => 'P4','kerawanan' => 'Roadside Unit (RSU)'],
            ['kritikal' => 'P5','kerawanan' => 'Server-Side Request Forgery (SSRF)'],
            ['kritikal' => 'P5','kerawanan' => 'Directory Listing Enabled'],
            ['kritikal' => 'P5','kerawanan' => 'Same-Site Scripting'],
            ['kritikal' => 'P5','kerawanan' => 'Misconfigured DNS'],
            ['kritikal' => 'P5','kerawanan' => 'Mail Server Misconfiguration'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Password Confirmation'],
            ['kritikal' => 'P5','kerawanan' => 'No Rate Limiting on Form'],
            ['kritikal' => 'P5','kerawanan' => 'Unsafe File Upload'],
            ['kritikal' => 'P5','kerawanan' => 'Cookie Scoped to Parent Domain'],
            ['kritikal' => 'P5','kerawanan' => 'Missing Secure or HTTPOnly Cookie Flag'],
            ['kritikal' => 'P5','kerawanan' => 'Clickjacking'],
            ['kritikal' => 'P5','kerawanan' => 'CAPTCHA'],
            ['kritikal' => 'P5','kerawanan' => 'Exposed Admin Portal'],
            ['kritikal' => 'P5','kerawanan' => 'Missing DNSSEC'],
            ['kritikal' => 'P5','kerawanan' => 'Fingerprinting/Banner Disclosure'],
            ['kritikal' => 'P5','kerawanan' => 'Username/Email Enumeration'],
            ['kritikal' => 'P5','kerawanan' => 'Potentially Unsafe HTTP Method Enabled'],
            ['kritikal' => 'P5','kerawanan' => 'Insecure SSL'],
            ['kritikal' => 'P5','kerawanan' => 'Reflected File Download (RFD)'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Security Headers'],
            ['kritikal' => 'P5','kerawanan' => 'Email Verification Bypass'],
            ['kritikal' => 'P5','kerawanan' => 'Missing Subresource Integrity'],
            ['kritikal' => 'P5','kerawanan' => 'Bitsquatting'],
            ['kritikal' => 'P5','kerawanan' => 'Parameter Pollution'],
            ['kritikal' => 'P5','kerawanan' => 'Content Spoofing'],
            ['kritikal' => 'P5','kerawanan' => 'Weak Login Function'],
            ['kritikal' => 'P5','kerawanan' => 'Session Fixation'],
            ['kritikal' => 'P5','kerawanan' => 'Failure to Invalidate Session'],
            ['kritikal' => 'P5','kerawanan' => 'Concurrent Logins'],
            ['kritikal' => 'P5','kerawanan' => 'Disclosure of Secrets'],
            ['kritikal' => 'P5','kerawanan' => 'Visible Detailed Error/Debug Page'],
            ['kritikal' => 'P5','kerawanan' => 'Disclosure of Known Public Information'],
            ['kritikal' => 'P5','kerawanan' => 'Token Leakage via Referer'],
            ['kritikal' => 'P5','kerawanan' => 'Sensitive Token in URL'],
            ['kritikal' => 'P5','kerawanan' => 'Non-Sensitive Token in URL'],
            ['kritikal' => 'P5','kerawanan' => 'Mixed Content (HTTPS Sourcing HTTP)'],
            ['kritikal' => 'P5','kerawanan' => 'Sensitive Data Hardcoded'],
            ['kritikal' => 'P5','kerawanan' => 'Internal IP Disclosure'],
            ['kritikal' => 'P5','kerawanan' => 'JSON Hijacking'],
            ['kritikal' => 'P5','kerawanan' => 'Via localStorage/sessionStorage'],
            ['kritikal' => 'P5','kerawanan' => 'Stored'],
            ['kritikal' => 'P5','kerawanan' => 'Reflected'],
            ['kritikal' => 'P5','kerawanan' => 'Flash-Based'],
            ['kritikal' => 'P5','kerawanan' => 'Cookie-Based'],
            ['kritikal' => 'P5','kerawanan' => 'IE-Only'],
            ['kritikal' => 'P5','kerawanan' => 'TRACE Method'],
            ['kritikal' => 'P5','kerawanan' => 'Insecure Direct Object References (IDOR)'],
            ['kritikal' => 'P5','kerawanan' => 'Action-Specific'],
            ['kritikal' => 'P5','kerawanan' => 'CSRF Token Not Unique Per Request'],
            ['kritikal' => 'P5','kerawanan' => 'Flash-Based'],
            ['kritikal' => 'P5','kerawanan' => 'App Crash'],
            ['kritikal' => 'P5','kerawanan' => 'Open Redirect'],
            ['kritikal' => 'P5','kerawanan' => 'Tabnabbing'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Security Speed Bump Page'],
            ['kritikal' => 'P5','kerawanan' => 'Browser Feature'],
            ['kritikal' => 'P5','kerawanan' => 'CSV Injection'],
            ['kritikal' => 'P5','kerawanan' => 'Captcha Bypass'],
            ['kritikal' => 'P5','kerawanan' => 'System Clipboard Leak'],
            ['kritikal' => 'P5','kerawanan' => 'User Password Persisted in Memory'],
            ['kritikal' => 'P5','kerawanan' => 'Weak Password Policy'],
            ['kritikal' => 'P5','kerawanan' => 'Password Policy Bypass'],
            ['kritikal' => 'P5','kerawanan' => 'Weak Password Reset Implementation'],
            ['kritikal' => 'P5','kerawanan' => 'Verification of Contact Method not Required'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Notification Email'],
            ['kritikal' => 'P5','kerawanan' => 'Weak Registration Implementation'],
            ['kritikal' => 'P5','kerawanan' => 'Weak 2FA Implementation'],
            ['kritikal' => 'P5','kerawanan' => 'Rosetta Flash'],
            ['kritikal' => 'P5','kerawanan' => 'Outdated Software Version'],
            ['kritikal' => 'P5','kerawanan' => 'Captcha Bypass'],
            ['kritikal' => 'P5','kerawanan' => 'Sensitive Application Data Stored Unencrypted'],
            ['kritikal' => 'P5','kerawanan' => 'Non-Sensitive Application Data Stored Unencrypted'],
            ['kritikal' => 'P5','kerawanan' => 'Screen Caching Enabled'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Exploit Mitigations'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Jailbreak Detection'],
            ['kritikal' => 'P5','kerawanan' => 'Lack of Obfuscation'],
            ['kritikal' => 'P5','kerawanan' => 'Runtime Instrumentation-Based'],
            ['kritikal' => 'P5','kerawanan' => 'Executable Download'],
            ['kritikal' => 'P5','kerawanan' => 'Weakness in Firmware Updates'],
            ['kritikal' => 'P5','kerawanan' => 'Data not encrypted at rest'],
            ['kritikal' => 'P5','kerawanan' => 'Insufficient Entropy'],
            ['kritikal' => 'P5','kerawanan' => 'Weak Hash'],
            ['kritikal' => 'P5','kerawanan' => 'Key Reuse'],
            ['kritikal' => 'P5','kerawanan' => 'Side-Channel Attack'],
            ['kritikal' => 'P5','kerawanan' => 'Incomplete Cleanup of Keying Material'],
            ['kritikal' => 'P5','kerawanan' => 'Telnet Enabled'],
            ['kritikal' => 'P5','kerawanan' => 'SSL Certificate Pinning'],
            ['kritikal' => 'P5','kerawanan' => 'Tapjacking'],
            ['kritikal' => 'P5','kerawanan' => 'Clipboard Enabled'],
            ['kritikal' => 'P5','kerawanan' => 'Auto Backup Allowed by Default'],
            ['kritikal' => 'P5','kerawanan' => 'Binary Planting'],
            ['kritikal' => 'P5','kerawanan' => 'RF Hub'],
            ['kritikal' => 'Varies','kerawanan' => 'Unsafe Cross-Origin Resource Sharing'],
            ['kritikal' => 'Varies','kerawanan' => 'HTTP Request Smuggling'],
            ['kritikal' => 'Varies','kerawanan' => 'Path Traversal'],
            ['kritikal' => 'Varies','kerawanan' => 'Directory Listing Enabled'],
            ['kritikal' => 'Varies','kerawanan' => 'SSL Attack (BREACH'],
            ['kritikal' => 'Varies','kerawanan' => 'OAuth Misconfiguration'],
            ['kritikal' => 'Varies','kerawanan' => 'Race Condition'],
            ['kritikal' => 'Varies','kerawanan' => 'Software Package Takeover'],
            ['kritikal' => 'Varies','kerawanan' => 'Cache Poisoning'],
            ['kritikal' => 'Varies','kerawanan' => 'LDAP Injection'],
            ['kritikal' => 'Varies','kerawanan' => 'Server-Side Template Injection (SSTI)'],
            ['kritikal' => 'Varies','kerawanan' => 'Failure to Invalidate Session'],
            ['kritikal' => 'Varies','kerawanan' => 'Disclosure of Secrets'],
            ['kritikal' => 'Varies','kerawanan' => 'Cross Site Script Inclusion (XSSI)'],
            ['kritikal' => 'Varies','kerawanan' => 'Exposed Sensitive Android Intent'],
            ['kritikal' => 'Varies','kerawanan' => 'Privilege Escalation'],
            ['kritikal' => 'Varies','kerawanan' => 'Exposed Sensitive iOS URL Scheme'],
            ['kritikal' => 'Varies','kerawanan' => 'Action-Specific'],
            ['kritikal' => 'Varies','kerawanan' => 'Excessive Resource Consumption'],
            ['kritikal' => 'Varies','kerawanan' => 'Cleartext Transmission of Sensitive Data'],
            ['kritikal' => 'Varies','kerawanan' => 'Representation Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Pre-existing Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Processing Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Aggregation Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Confirmation Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Systemic Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Context Ignorance'],
            ['kritikal' => 'Varies','kerawanan' => 'Implicit Bias'],
            ['kritikal' => 'Varies','kerawanan' => 'Bypass of physical access control'],
            ['kritikal' => 'Varies','kerawanan' => 'Weakness in physical access control'],
            ['kritikal' => 'Varies','kerawanan' => 'Weakness in Firmware Updates'],
            ['kritikal' => 'Varies','kerawanan' => 'Kiosk Escape or Breakout'],
            ['kritikal' => 'Varies','kerawanan' => 'Poorly Configured Disk Encryption'],
            ['kritikal' => 'Varies','kerawanan' => 'Poorly Configured Operating System Security'],
            ['kritikal' => 'Varies','kerawanan' => 'Recovery of Disk Contains Sensitive Material'],
            ['kritikal' => 'Varies','kerawanan' => 'Failure to Remove Sensitive Artifacts from Disk'],
            ['kritikal' => 'Varies','kerawanan' => 'Data not encrypted at rest'],
            ['kritikal' => 'Varies','kerawanan' => 'Insecure Implementation'],
            ['kritikal' => 'Varies','kerawanan' => 'Weak Hash'],
            ['kritikal' => 'Varies','kerawanan' => 'Insufficient Verification of Data Authenticity'],
            ['kritikal' => 'Varies','kerawanan' => 'Insecure Key Generation'],
            ['kritikal' => 'Varies','kerawanan' => 'Side-Channel Attack'],
    ];

    foreach ($data as $item) {
        Inherentrisiko::updateOrCreate(
            ['kerawanan' => $item['kerawanan']],  // Kolom untuk menentukan unik
            $item  // Data yang akan diperbarui atau ditambahkan
        );
    }

}
}
